Develop
biguapp/bigu-backend-nest pull request #5
Opened 2024-09-17 15:54 UTC by matheus-a-r

Operações de aceitação de carona, rejeição de carona, solicitação de carona e notificação por email.

2024-09-18 13:57 UTC, PauloHFS requested changes

2024-09-18 13:57 UTC, PauloHFS commented on src/database.module.ts
> +    imports: [MongooseModule.forRoot('mongodb+srv://italoramalho:utOBFAyYgHyt4BWl@saude-campina-db.wzaljqi.mongodb.net/?retryWrites=true&w=majority&appName=saude-campina-db')],
Carregue essa url de um .env, assim não precisamos expor a url no código fonte além de que não precisa ficar alterando toda vez que der pull de código novo.

Link util para fazer essa configuração:
https://docs.nestjs.com/techniques/configuration

2024-09-18 13:57 UTC, PauloHFS commented on src/resend.server.ts
> +const resend = new Resend('re_Nukcfmn7_7GsfZHBufESb93bfBUEx9ME1');
Isto é uma problema de segurança, por favor invalide esse token e gere um novemente, este novo você deve carregar-lo do .env

além disso creio que você deva modificar para `export const resend = ...` visto que esse client da sdk será utilizado para enviar os emails nos endpoints.

Link util: https://docs.nestjs.com/techniques/configuration

2024-09-18 13:57 UTC, PauloHFS commented on src/resend.server.ts
> +resend.emails.send({
Não entendi por que você está fazendo esse envio aqui? Creio que esse código deva ser migrado para o endpoints de cadastro de usuário ou apenas removido desse arquivo

2024-09-18 13:57 UTC, PauloHFS commented on src/resend/resend.interface.ts
> +  apiKey: 're_Nukcfmn7_7GsfZHBufESb93bfBUEx9ME1'
Isto é uma problema de segurança, por favor invalide esse token e gere um novemente, este novo você deve carregar-lo do .env

Link util: https://docs.nestjs.com/techniques/configuration

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    async findAll(@Res() response): Promise<UserResponseDto[]> {
Não sei qual o propósito mas não me faz sentido um endpoint que retorna todos usuários, poderiam me informar o por que isso?

Meu ponto de vista é que informações de usuários assim tem que está atrelados há alguma coisa do usuário autenticado, por exemplo, um bom endpoint de listagem de usuários é a listagem de usuários que relacionam com um motorista com uma corrida.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
> +  @ApiOperation({ summary: 'Retorna um usuário pelo email' })
Por que só pelo email? 

Vocês poderiam receber no params todos os parametros do usuário e fazer um find com o que bate com eles tipo 

`/url?id=xxxxxxx-xxxxxxxx-xxxxxxx&name=Joao%20Silva&email=joaosilva@email.com&matricula=999999999`

```json
{
"id": "xxxxxxx-xxxxxxxx-xxxxxxx",
"name": "João Silva",
"email": "joaosilva@email.com",
"matricula": "999999999"
}
```
Sendo cada campo não obrigatório, o client pode mandar nome e/ou email e/ou matricula, o find do mongoose consegue lidar com isso.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    async findOneByMatricula(
Por que só pelo matricula? 

Vocês poderiam receber nos params todos os parametros do usuário e fazer um find com o que bate com eles tipo 


`/url?id=xxxxxxx-xxxxxxxx-xxxxxxx&name=Joao%20Silva&email=joaosilva@email.com&matricula=999999999`

```json
{
"id": "xxxxxxx-xxxxxxxx-xxxxxxx",
"name": "João Silva",
"email": "joaosilva@email.com",
"matricula": "999999999"
}
```
Sendo cada campo não obrigatório, o client pode mandar nome e/ou email e/ou matricula, o find do mongoose consegue lidar com isso.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
> +  async findOneByEmail(
Esse endpoint está exposto, não precisa ser autenticado para acessa-lo, ou sejá qualquer 1 pode consultar, novamente, informar conteudo de usuários assim tem que ser avaliado as permissões de quem tá acessando.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    @ApiOperation({ summary: 'Retorna um usuário pela matrícula' })
Esse endpoint está exposto, não precisa ser autenticado para acessa-lo, ou sejá qualquer 1 pode consultar, novamente, informar conteudo de usuários assim tem que ser avaliado as permissões de quem tá acessando.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
> +  @ApiOperation({ summary: 'Retorna um usuário pelo ID' })
Por que só pelo matricula?

Vocês poderiam receber nos params todos os parametros do usuário e fazer um find com o que bate com eles tipo

`/url?id=xxxxxxx-xxxxxxxx-xxxxxxx&name=Joao%20Silva&email=joaosilva@email.com&matricula=999999999`

```json
{
"id": "xxxxxxx-xxxxxxxx-xxxxxxx",
"name": "João Silva",
"email": "joaosilva@email.com",
"matricula": "999999999"
}
```

Sendo cada campo não obrigatório, o client pode mandar id e/ou nome e/ou email e/ou matricula, o find do mongoose consegue lidar com isso.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    async findOne(@Res() response, @Param('id') id: string): Promise<UserResponseDto> {
Esse endpoint está exposto, não precisa ser autenticado para acessa-lo, ou sejá qualquer 1 pode consultar, novamente, informar conteudo de usuários assim tem que ser avaliado as permissões de quem tá acessando.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    async remove(@Res() response, @Param('id') id: string): Promise<UserResponseDto> {
Não está autenticado, qualquer pessoa com o id de um usuário pode remover o id, geralmente remoção de usuário não é um endpoints dessa forma, é um descadastro que realiza a operação de remoção do usuário e dos dados dele em outra collections.

Idealmente apenas o usuário autenticado poderia remover a si mesmo, sendo assim, você não pega o ID pelo params mas sim pelo token de authenticação dele.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    async update(
Sem authenticação, idealmente apenas o usuário authenticado pode modificar o seu proprio user, não precisa pegar o id da url params, mas sim dó token que o usuário já envia para se autenticar.

2024-09-18 13:57 UTC, PauloHFS commented on src/user/user.controller.ts
>    @Get('/user/self')
**sugestion:** poderia ser só /user mesmo

2024-09-18 13:57 UTC, PauloHFS commented on src/ride/ride.controller.ts
> +  @Put('/remove/member/:rideId/:memberId')
remove não o nome de uma rota muito boa sabe,

melhor: `/ride/:rideId/member/:memberId`

e PUT para fazer remoção também não é bom, preferivel o DELETE

2024-09-18 13:57 UTC, PauloHFS commented on src/ride/ride.controller.ts
> +  @Put('/decline/candidate/:rideId/:candidateId')
Essa rota num tá legal.

melhor: `/ride/:rideId/member/:memberId`

e no body da requisição tu passar o status que tu vai atualizar o canditado
status: "approved" | "declined"

2024-09-18 14:05 UTC, italoaraujooj commented on src/user/user.controller.ts
>    async findAll(@Res() response): Promise<UserResponseDto[]> {
É só pra facilitar a realização dos testes relacionados a criação de usuários durante o desenvolvimento, mas vai ser removida futuramente

2024-09-18 17:44 UTC, italoaraujooj commented on src/user/user.controller.ts
>    async remove(@Res() response, @Param('id') id: string): Promise<UserResponseDto> {
@matheus-a-r ve isso de mudar a forma de remover o user a partir do token dele pf

2024-09-18 17:45 UTC, italoaraujooj commented on src/user/user.controller.ts
>    @Get('/user/self')
@matheus-a-r alterei aqui, lembra de alterar no front

2024-09-18 17:47 UTC, italoaraujooj commented on src/ride/ride.controller.ts
> +  @Put('/remove/member/:rideId/:memberId')
Esse membro tá dentro de um array de Members na entidade corrida, mesmo sendo apenas a alteração de atributo é pra ser DELETE?

2024-09-18 19:05 UTC, italoaraujooj commented on src/user/user.controller.ts
>    async remove(@Res() response, @Param('id') id: string): Promise<UserResponseDto> {
Já resolvi, pessoal.

2024-09-18 19:52 UTC, italoaraujooj commented on src/ride/ride.controller.ts
> +  @Put('/decline/candidate/:rideId/:candidateId')
@matheus-a-r

2024-09-19 18:41 UTC, PauloHFS approved these changes

2024-09-19 18:41 UTC, PauloHFS commented on src/address/address.controller.ts
>    async update(
não precisaria de   @UseGuards(JwtAuthGuard)  nesse endpoint também não?

2024-09-19 18:41 UTC, PauloHFS commented on src/address/address.controller.ts
>    async removeAll(@Res() response): Promise<void> {
Não precisa de um   @UseGuards(JwtAuthGuard)  nesse endpoint não?

2024-09-19 18:46 UTC, merged

2024-09-20 00:29 UTC, italoaraujooj commented on src/address/address.controller.ts
>    async removeAll(@Res() response): Promise<void> {
esse endpoint vai deixar de existir, era só p facilitar uns testes